### ISSUE TITLE
TSLEAD seems not recognized

### ISSUE THREAD

**Issue by rrremedio** [andrea-luciani/bimets#1]
TSLEAD seems to be not recognized by LOAD_MODEL.

```
modelo_alimentos <- "
MODEL

EQUATION> ipca_alimentos 
EQ> ipca_alimentos = c1*TSDELTA(TSLAG(ipca)) + 
c2*TSDELTA(TSLEAD(expectativas_ipca)) +
c3*(TSLAG(crbreais_var_anual)) +
c4*MOVAVG(TSLAG(hiato), 2) +
c5*temperatura^2
COEFF> c1 c2 c3 c4 c5
RESTRICT> c1 + c2 + c3 = 1

END
"
modelo_alimentos <- LOAD_MODEL(modelText = modelo_alimentos)

Error in LOAD_MODEL(modelText = modelo_alimentos) : 
  LOAD_MODEL(): unsupported functions in EQ definition: "ipca_alimentos=c1*TSDELTA(TSLAG(ipca))+c2*TSDELTA(TSLEAD(expectativas_ipca))+c3*(TSLAG(crbreais_var_anual))+c4*MOVAVG(TSLAG(hiato),2)+c5*temperatura^2+c6*d2002q4+c7*d2008q2+c8*d2013q1+c9*d2010q4+c10*d2007q3" in behavioral "ipca_alimentos": TSLEAD()
```

**Comment by andrea-luciani** [comment]
Hi rrremedio,

as stated in the reference manual, page 104:
https://cran.r-project.org/web/packages/bimets/bimets.pdf

TSLEAD is not allowed in MDL definition.

We are planning to insert Forward-Looking Models in bimets' future releases, but atm only TSLAG and the MDL functions cited in the reference manual are allowed.

Have a good day.

> TSLEAD seems to be not recognized by LOAD_MODEL.
> 
> ```
> modelo_alimentos <- "
> MODEL
> 
> EQUATION> ipca_alimentos 
> EQ> ipca_alimentos = c1*TSDELTA(TSLAG(ipca)) + 
> c2*TSDELTA(TSLEAD(expectativas_ipca)) +
> c3*(TSLAG(crbreais_var_anual)) +
> c4*MOVAVG(TSLAG(hiato), 2) +
> c5*temperatura^2
> COEFF> c1 c2 c3 c4 c5
> RESTRICT> c1 + c2 + c3 = 1
> 
> END
> "
> modelo_alimentos <- LOAD_MODEL(modelText = modelo_alimentos)
> 
> Error in LOAD_MODEL(modelText = modelo_alimentos) : 
>   LOAD_MODEL(): unsupported functions in EQ definition: "ipca_alimentos=c1*TSDELTA(TSLAG(ipca))+c2*TSDELTA(TSLEAD(expectativas_ipca))+c3*(TSLAG(crbreais_var_anual))+c4*MOVAVG(TSLAG(hiato),2)+c5*temperatura^2+c6*d2002q4+c7*d2008q2+c8*d2013q1+c9*d2010q4+c10*d2007q3" in behavioral "ipca_alimentos": TSLEAD()
> ```

Hi
