### ISSUE TITLE
How to extend the data of seasonal dummy variables in bimets

### ISSUE THREAD

**Issue by murao164jp** [andrea-luciani/bimets#10]
Using TSEXTEND() function, we can extend the data of qualitative variables, but cannot for seasonal dummy variables.
----------------------
Therefore, I created an extend part for the old data set “my_data” with seasonal dummy variables, outside of the bimets environment. I combined it with “my_data”, and named the new data set as “my_data_V2”. In short, the new data set “my_data_V2” has both of the old part and new part of time range. For the new part of time range, the qualitative variables have missing values “NA”. Using “my_data_V2”, I uploaded it into the bimets environment and named as “bimodal_V2”. I estimated the same model with the old part of time range, and stored the estimation result to “bimodal_V2”.
----------------------
Note that the old model “bimodal” is based on “my_data”, and the new model “bimodal_V2” is based on “my_data_V2”. I dropped the seasonal dummy variables for “bimodel”.  The old model “bimodal” worked all right for forecast even I changed the data of exogenous qualitative variables, using TSEXTEND() function.
----------------------
Using “bimodal_V2” and TSEXTEND() function, I extended the data of exogenous qualitative variables (TAX, MrP, G) for the new part of time range.  However, I got the following error message of definition of the qualitative variables. 
-----------------------------
      SIMULATE(): exogenous variable "TAX" is not fully defined in the TSRANGE. There are undefined values at year-period 2024-4
------------------------------
Using TABIT() function, I checked the data set “modelData” in “bimodal_V2”, and found that the exogenous qualitative variables (TAX, MrP, G) had missing value “NA” for the extended part of time range. The seasonal dummy variables have the values specified in “my_data_V2” for the extended part of time range.
-------------------------------
My questions or requests are as follows.

(1) Please make a new option for TSEXTEND() function such that it extends the data of seasonal dummy variables.
(2) I would like to know how to solve the current problem.

-------------------------------
My R script, its log file, and the data are attached for the concrete information of problem. 

Thanks 

[forecast_out_sample_ISLM.TXT](https://github.com/andrea-luciani/bimets/files/14596065/forecast_out_sample_ISLM.TXT)
[data_ISLM.csv](https://github.com/andrea-luciani/bimets/files/14596021/data_ISLM.csv)
[record_20024-03-14.txt](https://github.com/andrea-luciani/bimets/files/14596038/record_20024-03-14.txt)

**Comment by andrea-luciani** [comment]
dear @murao164jp 

`TSEXTEND` doen not change current values in a time series. This function extends a time series outside its definition time range.

Lines `423:428` in `forecast_out_sample_ISLM.TXT`: In data.frame `data_obs_V2`, and in the related list `data_preBi_V2`, exogenous variables already are already defined up tp `2024-4`, and have missing values.

Therefore, when you apply `TSEXTEND` in lines `446`, you are actually chaning nothing: time series are already defined up to `2024-4`, and exogenous variables will still have misisng values in simulation `TSRANGE`. Thus, `SIMULATE` issues an error.

If you want to replace missing values with arbitrary values in your time series, you have to manually remove missing values, or you may want to take a look at the `TSTRIM` function: after the missing removal, then you can apply the `TSEXTEND`.

**Comment by murao164jp** [comment]
Thank you for your comment.

I tried several ideas after posting my question, and I found a way to solve it. 

It uses the combination of TSJOIN()function, TSEXTEND()function, TIMESERIES()function. My example is shown in the below.

------------------------
# A way to extend the data of dummy variables in "bimets" 
# The use of TSJOIN(), TSEXTEND(), and TIMESERIES() for it.

bimodel$modelData <- within(bimodel$modelData,{
 dum_Q1_part2 = TSEXTEND(TIMESERIES(0, 1, 0, 0, 0, 1, 0, 0, 0,  START = c(2022, 4), FREQ='Q'), 
                              BACKTO =  c(2022, 4), UPTO = c(2024, 4))
 dum_Q1 <- TSJOIN(dum_Q1, dum_Q1_part2, ALLOWGAP = FALSE)

 dum_Q2_part2 = TSEXTEND(TIMESERIES(0, 0, 1, 0, 0, 0, 1, 0, 0,  START = c(2022, 4), FREQ='Q'), 
                             BACKTO =  c(2022, 4), UPTO = c(2024, 4))
 dum_Q2 <- TSJOIN(dum_Q2, dum_Q2_part2, ALLOWGAP = FALSE)

 dum_Q3_part2 = TSEXTEND(TIMESERIES(0, 0, 0, 1, 0, 0, 0, 1, 0,  START = c(2022, 4), FREQ='Q'), 
                              BACKTO =  c(2022, 4), UPTO = c(2024, 4))
 dum_Q3 <- TSJOIN(dum_Q3, dum_Q3_part2, ALLOWGAP = FALSE)

 }) # end of within()
# end of dealing with "bimodel$modelData"

------------
Currently I have two suggestions.

(1) Please write your version of the above idea in the manual of bimets.

(2) It is nice to have this kind of option in TSEXTEND()function.

Thank you again.

Hiroshi Murao

**Comment by andrea-luciani** [comment]
hi @murao164jp 

you may want to remove the `TSEXTEND` in your code, it does not change the target time series. In the following code, similar to yours, `ts1` and `ts1ext` are the same time series: 

```
> ts1=(TIMESERIES(0, 1, 0, 0, 0, 1, 0, 0, 0, START = c(2022, 4), FREQ='Q'))
> ts1ext=TSEXTEND(ts1,BACKTO = c(2022, 4), UPTO = c(2024, 4))
> TABIT(ts1,ts1ext)

      Date, Prd., ts1            , ts1ext

   2022 Q4, 4   ,  0             ,  0
   2023 Q1, 1   ,  1             ,  1
   2023 Q2, 2   ,  0             ,  0
   2023 Q3, 3   ,  0             ,  0
   2023 Q4, 4   ,  0             ,  0
   2024 Q1, 1   ,  1             ,  1
   2024 Q2, 2   ,  0             ,  0
   2024 Q3, 3   ,  0             ,  0
   2024 Q4, 4   ,  0             ,  0
```

If you want to create a time series that is one only in an arbitrary quarter, you may want to take a look at the following:

```
> start=c(2022,4)
> end=c(2024,4)
> length=NUMPERIOD(start,end,4)+1
> tsBase=TSERIES(rep(0,length),START=start,FREQ='Q')

#set this variable to selected quarter, 1..4
> quarterToBeOne=3

> dummyQuarter3=tsBase
> dummyQuarter3[which(GETDATE(dummyQuarter3,format='%q')==quarterToBeOne)]=1
> TABIT(dummyQuarter3)

      Date, Prd., dummyQuarter3

   2022 Q4, 4   ,  0
   2023 Q1, 1   ,  0
   2023 Q2, 2   ,  0
   2023 Q3, 3   ,  1
   2023 Q4, 4   ,  0
   2024 Q1, 1   ,  0
   2024 Q2, 2   ,  0
   2024 Q3, 3   ,  1
   2024 Q4, 4   ,  0

```

Hope this will help.

**Comment by murao164jp** [comment]
Thank you for your suggestions. They are very helpful. I will use these techniques for my R scripts.
