### ISSUE TITLE
Is it possible to create a bimets data frame?

### ISSUE THREAD

**Issue by juansqw** [andrea-luciani/bimets#2]
I am currently with a model with about 29 variables. Currently I have to create one bimet object for each variable in order to use them on a model. Each of these variable have the same arguments, so it makes the code longer than it needs to be.

This issue might be solved (or improved) if there were a way that I could convert a data frame into a bimets object.

Is it possible to create a bimets data frame?

**Comment by andrea-luciani** [comment]
> I am currently with a model with about 29 variables. Currently I have to create one bimet object for each variable in order to use them on a model. Each of these variable have the same arguments, so it makes the code longer than it needs to be.
> 
> This issue might be solved (or improved) if there were a way that I could convert a data frame into a bimets object.
> 
> Is it possible to create a bimets data frame?

Hi Juansqw.

I appreciate your interest in the bimets package.

I'm not sure I understand this correctly, but if you want to convert a data.frame into a time series list suitable to a bimets model, you may want to try the following:

```
library(bimets)

#create a simple monthly dataframe
my_df <- data.frame(dates=c("1/1/2000","1/2/2000","1/3/2000","1/4/2000","1/5/2000","1/6/2000")
                 ,ts1=(1:6)
                 ,ts2=pi*(1:6)
                 ,ts3=seq(0,-1,length.out=6)
                 )

#check df data
print(my_df)

#convert to bimets model data
my_bimets_modeldata <- lapply(as.list(xts(my_df[,-1], order.by=as.Date(my_df[,1],"%m/%d/%Y"))), as.bimets)      

#the data.frame is now loadable into a bimets model
my_model_mdl <- "
MODEL

BEHAVIORAL>ts1
EQ>ts1 = c0 + c1*ts2 + c2*ts3
COEFF>c0 c1 c2

END
"

my_model <- LOAD_MODEL(modelText = my_model_mdl)

my_model <- LOAD_MODEL_DATA(my_model, my_bimets_modeldata)

my_model <- ESTIMATE(my_model, TSRANGE = c(2000,1,2000,6))
```

**Comment by juansqw** [comment]
Hola Andrea
This is not what I was thinking, but it certainly does the trick.

Thank you for your help.

**Comment by andrea-luciani** [comment]
Dear @juansqw 

A new version of the `bimets` package is now available on the CRAN website (i.e., the Comprehensive R Archive Network):
https://cran.r-project.org/package=bimets

`bimets ver. 4.1.1` includes new functions to import/export time series lists (also having different frequency and time range) from/to CSV (Comma-Separated Values) files.

To update the package to the latest CRAN version, use the following command in R:
`install.packages("bimets")`

More details are available in the package reference manual:
https://cran.r-project.org/web/packages/bimets/refman/bimets.html#BIMETS2CSV 
https://cran.r-project.org/web/packages/bimets/refman/bimets.html#CSV2BIMETS 

Change-Log is available here:
https://cran.r-project.org/web/packages/bimets/news/news.html 

Getting started with bimets:
https://cran.r-project.org/web/packages/bimets/vignettes/bimets.pdf

Have a good day.
