### ISSUE TITLE
How to read a regular data set into bimets

### ISSUE THREAD

**Issue by murao164jp** [andrea-luciani/bimets#3]
I have a question.  How do we read the regular data set, say the data set of csv format,  into a data set such that bimets works properly? 

Suppose that we have 30 variables and each variable 100 observations.  
We don't want to use TIMESERIES() function to load the data set to bimets.
If we use TIMESERIES() function, then the task of writing codes will never end. 

This kind of task is very basic. But, the manual of bimets does not show it.
The manual shows only the use of TIMESERIES() function.

Could you show me how to read the data set into bimets? 
Please also write the task on the manual of bimets.

**Comment by andrea-luciani** [comment]
Hi murao164jp

I appreciate your interest in the bimets package.

please take a look at a similar issue here #2 on GitHub: you can read a csv into a data.frame using standard R commands, then import it into a bimets model.

**Comment by murao164jp** [comment]
The function shown in issue #2 solved my problem. Thank you for your information.

I would like to add the following information for typical users of quarterly data. 

When we use the quarterly data with "1994Q2", 
it is nice to use the following function for converting "1994Q2" to "1994-04-01".
Because the function of issue #2 requires the date type of "1994-04-01" for the first variable.

-------------------------------------------------------------
# convert "1994Q2" to "1994-04-01", i.e., convert date_info to date_Ymd
date_info <- data_use$date
# date_info contains a value such as "1994Q2".
head(date_info)

# The following function is found from Internet.
date_Ymd <- as.Date(
sapply(strsplit(date_info, 'Q'),
function(x) paste(1, seq(1,10,3)[as.integer(x[2])], x[1], sep = '-')),
format = '%d-%m-%Y')
# end of the function

# check the output of as.Date() function
head(date_Ymd)
# date_Ymd contains a value such as "1994-04-01".
---------------------------------------------------------------

After getting "date_Ymd", we use it for the main data frame, say "my_df".  
Then we use "my_df" for converting it into a bimets-type data set, using the function shown in issue #2.

**Comment by andrea-luciani** [comment]
Hi [murao164jp](https://github.com/murao164jp).

I am not sure if I have understood your suggestion, but you may want to take a look at standard zoo functions:

```
> as.Date(as.yearqtr('1994Q2'))
[1] "1994-04-01"
```

Conversely, the bimets `GETDATE` function will help you convert time series periods in a custom format:

```
> ts1=TIMESERIES(1:10,START=c(1994,1),FREQ=4)
> print(GETDATE(ts1,2,'%YQ%q'))
[1] "1994Q2"
>
```

**Comment by murao164jp** [comment]
Hi Andrea Lucian,

The use of "as.Date(as.yearqtr(1994Q3))" works all right for the task under the consideration.  
When I wrote the additional information in the above, I didn't know zoo:as.yearqtr() function. As a result, I used general functions for the task. Either method works all right. 

It would be nice if Package “bimets” would provide a function, say “fromDATAtoBIMETS”, so that the data set of data-frame type would be easily converted into the data set of bimets-type.

**Comment by murao164jp** [comment]
* { font-size: 13px; font-family: 'MS Pゴシック', sans-serif;}p, ul, ol, blockquote { margin: 0;}a { color: #0064c8; text-decoration: none;}a:hover { color: #0057af; text-decoration: underline;}a:active { color: #004c98;}
Dear Andrea Luciani,

 

Yes, your method works. When I wrote the suggestion, I didn’t know zoo:as.yearqtr() function. As a result, I used a method with general functions for the task. As you see in GitHub, I modified the suggestion, including your method, so that the whole process of the task would be simpler. 

 

Thank you again for your useful information.

 

Hiroshi Murao




----- Original Message -----




From: "Andrea Luciani" ***@***.***>

To: "andrea-luciani/bimets" ***@***.***>

Cc: "村尾 博" ***@***.***>; "State change" ***@***.***>

Date: 2023/07/19 水 19:17

Subject: Re: [andrea-luciani/bimets] How to read a regular data set into bimets (Issue #3)







Hi murao164jp.

I am not sure if I have understood your suggestion, but you may want to take a look at standard zoo functions:
> as.Date(as.yearqtr('1994Q2'))
[1] "1994-04-01"
Conversely, the bimets GETDATE function will help you convert time series periods in a custom format:
> ts1=TIMESERIES(1:10,START=c(1994,1),FREQ=4)
> print(GETDATE(ts1,2,'%YQ%q'))
[1] "1994Q2"
