### ISSUE TITLE
Full incidence matrix

### ISSUE THREAD

**Issue by ferdinand-fichtner** [andrea-luciani/bimets#8]
Hey Andrea

thank you for creating this awesome package, which I am just starting to use.

I have an issue (more a feature request, to be honest): The incidence matrix accessible through MyModel$incidence_matrix only includes the (contemporary) links between the endogenous variables. While this is obviously what you need for solving the model, it is not sufficient to create a network graph of the model like the one you have in the documentation, which also includes exogenous variables and intertemporal linkages. 

I would find it interesting if you could additionally include this "full incidence matrix" as an output of the LOAD_MODEL function. This could then be used to creatin the full graph of the model, e.g. by using it as an argument in the "graph_from_adjacency_matrix" function of the igraph package (which expects the incidence matrix in transposed form compared to the version created by LOAD_MODEL, but that's obviously not a big deal).

Do you think this is something that could be included without too much work? It would be an attractive feature from my point of view. But anyhow: The package is great and looks very useful to me!

Best regards
Ferdinand FIchtner

**Comment by andrea-luciani** [comment]
Dear @ferdinand-fichtner 

Thanks for your interest in the `bimets` package.

I got your point. As you said, atm `incidence_matrix` only contains references for actual endogenous variables that contemporary impact the dependent variable.

To meet your goals, you may want to take a look at the behaviorals/identities `eqComponentNames` attribute in order to build up a chart similar to the chart you found on the bimets pdfs. Take a look at the following code:

```
rm(list=ls(all.names = T))

library(bimets)
library(igraph)
library(extrafont)
library(hrbrthemes)
library(ggalt)
library(ggplot2)
library(plotly)

#define model
klein1_def <- "
MODEL

COMMENT> Consumption
BEHAVIORAL> cn
TSRANGE 1921 1 1941 1
EQ> cn = a1 + a2*p + a3*TSLAG(p,1) + a4*(w1+w2)
COEFF> a1 a2 a3 a4

COMMENT> Investment
BEHAVIORAL> i
TSRANGE 1921 1 1941 1
EQ> i = b1 + b2*p + b3*TSLAG(p,1) + b4*TSLAG(k,1)
COEFF> b1 b2 b3 b4

COMMENT> Demand for Labor
BEHAVIORAL> w1
TSRANGE 1921 1 1941 1
EQ> w1 = c1 + c2*(y+t-w2) + c3*TSLAG(y+t-w2,1)+c4*time
COEFF> c1 c2 c3 c4

COMMENT> Gross National Product
IDENTITY> y
EQ> y = cn + i + g - t 

COMMENT> Profits
IDENTITY> p
EQ> p = y - (w1+w2)

COMMENT> Capital Stock 
IDENTITY> k
EQ> k = TSLAG(k,1) + i
END
"

#load model
myModel <- LOAD_MODEL(modelText = klein1_def)

#define vertices, i.e. vendog + vexog
vertices_names  <- c(myModel$vendog,myModel$vexog)
vertices_type   <- c(rep("en",length(myModel$vendog)),rep("ex",length(myModel$vexog)))

vertices  <- data.frame(name=vertices_names,
                        type=vertices_type)

#define relations between vertices
relations_from  <- c()
relations_to    <- c()

for (idx in names(myModel$behaviorals))
{
  #get eq components names
  localIncidenceVars=myModel$behaviorals[[idx]]$eqComponentsNames
  #remove dependant 
  localIncidenceVars=setdiff(localIncidenceVars,idx)
  
  for (from in localIncidenceVars)
  {
    relations_from  <- c(relations_from,from)
    relations_to    <- c(relations_to,idx)
  }
}

for (idx in names(myModel$identities))
{
  localIncidenceVars=myModel$identities[[idx]]$eqComponentsNames
  localIncidenceVars=setdiff(localIncidenceVars,idx)
  
  for (from in localIncidenceVars)
  {
    relations_from  <- c(relations_from,from)
    relations_to    <- c(relations_to,idx)
  }
}
 
relations <- data.frame(from=relations_from,
                        to=relations_to)


#add attribute to graph, TRUE if from-node is an endogenous
relations$fromIsEndogenous <- FALSE
relations$fromIsEndogenous[which(relations$from %in% vertices$name[which(vertices$type=='en')])] <- TRUE

#create graph
g <- graph.data.frame(relations, directed=TRUE, vertices=vertices)

#define edge colors, dark blue if circular
edge_colors <- rep("pink",length(relations$from))
edge_colors[which(E(g)$fromIsEndogenous==TRUE)] <- "skyblue"

#plot stuff
set.seed(18)
plot(g,
     main="Klein model full incidence graph",
     edge.arrow.size=0.3, 
     edge.arrow.width=3,
     edge.width=c(1.3, 2.1)[1+(E(g)$fromIsEndogenous==TRUE)],
     edge.color=edge_colors,
     vertex.color=c("pink", "skyblue")[1+(V(g)$type=="en")],
     vertex.size=c(35,30)[1+(V(g)$type=="en")], 
     vertex.frame.color="#ffffff",
     vertex.label.color=c("#662222", "#222266")[1+(V(g)$type=="en")],
     vertex.label.cex=0.8, 
     vertex.label.family="Arial Black", 
     edge.curved=-0.2,
     layout=layout.davidson.harel
)

```

![Rplot](https://github.com/andrea-luciani/bimets/assets/98331176/40c0a861-3d8d-4f7c-96f1-e5cb34250c0f)

**Limitations**: the code above does not work fine (it misses self-loops) if you have `TSDELTA`, `TSDELTAP`, `TSDELTALOG` functions on the left side of your equations (due to the fact that we remove the dependent variable by using the `setdiff` command), or if you have a self-dependent equation, e.g. `EQ> Y = X + 0.1*Y`

I have inserted an "extend incidence matrix" task in the bimets to-do list, so hopefully, we will have this new feature in the upcoming bimets versions.

Have a good day.

**Comment by ferdinand-fichtner** [comment]
Dear Andrea,

thank you very much for looking into this and working out a solution - which works nicely for me! Looking forward to an official extension of the package, but at this stage, your suggestion works well!

Best 
Ferdinand

**Comment by andrea-luciani** [comment]
last but not least, by changing the value in `set.seed(18)` ggplot randomly rearranges graphical components, so you can try different layouts.
